Unityやライブラリなどサードパーティのバージョンアップ
extreal-dev/Extreal.Integration.AssetWorkflow.Addressables.Test pull request #4
Opened 2023-06-17 14:12 UTC by kiyohome

ソースコードの変更に合わせてテストコードを変更しました。
https://github.com/extreal-dev/Extreal.Integration.AssetWorkflow.Addressables/pull/3

2023-06-20 08:53 UTC, sus-taguchi-t requested changes

2023-06-20 08:53 UTC, sus-taguchi-t commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +          m_Data: True
ここはローカルホスト立てるかどうかを設定するところですが、`False` にしておいた方が良いと思います。

2023-06-20 08:53 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.3",
`Core.Common` の最新は `1.1.0-next-4` だったと思います。

2023-06-20 08:53 UTC, sus-taguchi-t commented on Assets/Tests/Runtime/Custom/ResourceProviders/CryptoAssetBundleResourceTest.cs
書く場所がないのでここに書きます。
コードカバレッジが通っていないところがあるようですが、大丈夫でしょうか？

2023-06-20 08:53 UTC, sus-taguchi-t commented on Assets/Tests/Runtime/AssetProviderTest.cs
> +        private const string Cube3Name = "Cube3";
ここで Cube を分けているのは何か理由があるのでしょうか？

2023-06-20 11:47 UTC, kiyohome commented on Assets/Tests/Runtime/Custom/ResourceProviders/CryptoAssetBundleResourceTest.cs
https://github.com/extreal-dev/Extreal.Integration.AssetWorkflow.Addressables/pull/3
ソースコードのPRの説明で書いてたんですが分かりにくかったですかね。
カバレッジ未達の部分のソースについて作成者として意見が欲しいです。
カバレッジ未達部分を見るとTypeがNoneについての処理っぽいです。
プロダクション側のソースとテストコードで今回の未達に影響するような変更は入れてないつもりです。
テストがすべてパスしてるのに通らなくなったのであればAddressablesの変更影響だと思うので削除したいのですが、懸念ありますか？

2023-06-20 11:50 UTC, kiyohome commented on Assets/Tests/Runtime/AssetProviderTest.cs
> +        private const string Cube3Name = "Cube3";
ソース側のPRの説明に書いてた下記の対応で分けてます。
`AssetProviderTestでキャッシュをクリアしてもダウンロード状態が戻らないためAssetGroupをテスト毎に分けるように変更`

サンプルアプリだとキャッシュクリアが効いていて、アプリ実行のたびにDLが走る（DLサイズが0でない）んですが、テストコードだとキャッシュクリアは効いてますがDLサイズが0になってしまいテストが落ちます。そのため、テストごとにAssetGroupを分けて（対象のCubeも分けて）テストをパスしました。キャッシュクリアの動きはテスト対象でないため。

2023-06-20 11:55 UTC, kiyohome commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +          m_Data: True
2022LTSからホストの制御が改善しているのでTrueでもいいと思いました。
ポート重複で起動しないことがあるんですが、Port欄横のResetを押せばPort番号が変わってすぐに起動できます。
このPJ自体、Addressablesのテスト用でホストを起動する前提なのでFalseにしておく必要があまりないと感じています。

2023-06-20 11:58 UTC, kiyohome commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.3",
Fixed!
https://github.com/extreal-dev/Extreal.Integration.AssetWorkflow.Addressables.Test/pull/4/commits/44003fd0bd9f489e6f3cd024150cbd634ec74254

2023-06-21 02:46 UTC, sus-taguchi-t commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +          m_Data: True
そうなんですね！
Addressables がそのような仕様になっているのであればこのままで大丈夫です！

2023-06-21 04:00 UTC, sus-taguchi-t commented on Assets/Tests/Runtime/AssetProviderTest.cs
> +        private const string Cube3Name = "Cube3";
ありがとうございます。
理解しました！

2023-06-21 06:51 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.3",
確認しました！

2023-06-21 06:51 UTC, sus-taguchi-t commented on Assets/Tests/Runtime/Custom/ResourceProviders/CryptoAssetBundleResourceTest.cs
`LogType.None` を削除し、カバレッジ未達箇所も削除して大丈夫です！

2023-06-21 06:52 UTC, sus-taguchi-t approved these changes

2023-06-21 07:15 UTC, kiyohome commented on Assets/Tests/Runtime/Custom/ResourceProviders/CryptoAssetBundleResourceTest.cs
対応しました。
https://github.com/extreal-dev/Extreal.Integration.AssetWorkflow.Addressables/commit/8629d96d227e0da5032cc0b23706eaad87f8e57c
Addressablesはdevelopにマージ済みだったので、PRのマージコミットに足しました。

2023-06-21 07:15 UTC, merged